
dm "log; clear;";
options symbolgen mprint mlogic;


%macro test;

    %if &cond %then %do;
        %put TRUE branch;
    %end;
    %else %do;
        %put FALSE branch;
    %end;

%mend;

%test;


dm "log; clear;";
/* -------------------------------
   Macro: generate steps dynamically
-------------------------------- */
%macro test_ok;

    /* Masked expression */
    %let cond = %str(5 > 3);

    /* Decide branch using macro logic */
    %if %unquote(&cond) %then %do;

        %put NOTE: TRUE branch selected;

        /* DATA step generated by macro */
        data want;
            set sashelp.class;
            flag = 1;
        run;

        /* PROC PRINT generated by macro */
        proc print data=want;
            title "TRUE branch output (flag=1)";
        run;

    %end;

    %else %do;

        %put NOTE: FALSE branch selected;

        data want;
            set sashelp.class;
            flag = 0;
        run;

        proc print data=want;
            title "FALSE branch output (flag=0)";
        run;

    %end;

%mend;

/* Optional: capture generated code */
filename mprint 'C:\Data\P_unquote.sas';
options mprint mfile;

/* Run macro */
%test_ok;
