*Ex23_Macro_Generates_Code.sas;

/**************************************************
* This program uses a SAS macro to dynamically generate 
* and execute code that:
*
* - Reads multiple text files from a ZIP archive
* - Creates one SAS dataset per year
* - Produces a sample listing (first 5 observations) for each dataset
*****************************************************/
dm "log; clear; output; clear;";
Options nocenter nodate nonumber nosymbolgen;
%Let Path = c:\Data;
%Let Pathx = c:\users\pmuhuri\SASCourse\Week11;
Libname mylib "&Path";
%macro readraw (first=, last=);

/********************************************************************** 
* Assigns a fileref to the ZIP archive & enables reading files 
* without extracting them.
* SASZIPAM is a SAS FILENAME access method (engine) that lets 
* you treat a ZIP file like a directory and read its contents 
* without unzipping it manually.
**********************************************************************/

Filename ZIPFILE SASZIPAM "&Path\names.zip"; 

 /* Macro loop generates SAS code for each year */
   %do year=&first %to &last;
	 DATA mylib.DSN&Year;
 	    INFILE ZIPFILE(yob&year..txt) DLM=',';
  	    INPUT name $ gender $ number;
	 RUN;
	 title "Listing from Data Set (Newborns' Names) for &Year";

 /************************************************************* 
 * The following line nests macro functions with DATA step functions to 
 * create a formatted, dynamic title. It puts today’s date (nicely formatted)
 * on the second title line.
 ************************************************************************/

	 title2 "%sysfunc(left(%qsysfunc(date(),worddate18.)))";
	    proc print data=mylib.DSN&Year(obs=5) noobs; 
		format number comma7.;
        run;
    %end ;
%mend readraw;

/**************************************************************
* These following two statements are used together to capture the  
* SAS code generated by the macro above and write it to an external file.
****************************************************************/

filename mprint "&Pathx\Ex23_Generated_Code.sas";
options mprint mfile;
%readraw(first=2000, last=2005)
