title "MEPS, 2000";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_00 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt00f;
var totexp00;
domain nmiss_exp('1') ;
ods output domain=_overall_00;
run;
title "MEPS, 2001";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_01 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt01f;
var totexp01;
domain nmiss_exp('1') ;
ods output domain=_overall_01;
run;
title "MEPS, 2002";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_02 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt02f;
var totexp02;
domain nmiss_exp('1') ;
ods output domain=_overall_02;
run;
title "MEPS, 2003";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_03 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt03f;
var totexp03;
domain nmiss_exp('1') ;
ods output domain=_overall_03;
run;
title "MEPS, 2004";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_04 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt04f;
var totexp04;
domain nmiss_exp('1') ;
ods output domain=_overall_04;
run;
title "MEPS, 2005";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_05 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt05f;
var totexp05;
domain nmiss_exp('1') ;
ods output domain=_overall_05;
run;
title "MEPS, 2006";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_06 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt06f;
var totexp06;
domain nmiss_exp('1') ;
ods output domain=_overall_06;
run;
title "MEPS, 2007";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_07 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt07f;
var totexp07;
domain nmiss_exp('1') ;
ods output domain=_overall_07;
run;
title "MEPS, 2008";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_08 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt08f;
var totexp08;
domain nmiss_exp('1') ;
ods output domain=_overall_08;
run;
title "MEPS, 2009";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_09 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt09f;
var totexp09;
domain nmiss_exp('1') ;
ods output domain=_overall_09;
run;
title "MEPS, 2010";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_10 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt10f;
var totexp10;
domain nmiss_exp('1') ;
ods output domain=_overall_10;
run;
title "MEPS, 2011";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_11 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt11f;
var totexp11;
domain nmiss_exp('1') ;
ods output domain=_overall_11;
run;
title "MEPS, 2012";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_12 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt12f;
var totexp12;
domain nmiss_exp('1') ;
ods output domain=_overall_12;
run;
title "MEPS, 2013";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_13 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt13f;
var totexp13;
domain nmiss_exp('1') ;
ods output domain=_overall_13;
run;
title "MEPS, 2014";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_14 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt14f;
var totexp14;
domain nmiss_exp('1') ;
ods output domain=_overall_14;
run;
title "MEPS, 2015";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_15 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt15f;
var totexp15;
domain nmiss_exp('1') ;
ods output domain=_overall_15;
run;
title "MEPS, 2016";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_16 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt16f;
var totexp16;
domain nmiss_exp('1') ;
ods output domain=_overall_16;
run;
title "MEPS, 2017";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_17 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt17f;
var totexp17;
domain nmiss_exp('1') ;
ods output domain=_overall_17;
run;
title "MEPS, 2018";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_18 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt18f;
var totexp18;
domain nmiss_exp('1') ;
ods output domain=_overall_18;
run;
title "MEPS, 2005";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_05 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt05f;
var totexp05;
domain nmiss_exp('1') ;
ods output domain=_overall_05;
run;
title "MEPS, 2007";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_07 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt07f;
var totexp07;
domain nmiss_exp('1') ;
ods output domain=_overall_07;
run;
title "MEPS, 2009";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_09 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt09f;
var totexp09;
domain nmiss_exp('1') ;
ods output domain=_overall_09;
run;
title "MEPS, 2012";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_12 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt12f;
var totexp12;
domain nmiss_exp('1') ;
ods output domain=_overall_12;
run;
title "MEPS, 2014";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_14 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt14f;
var totexp14;
domain nmiss_exp('1') ;
ods output domain=_overall_14;
run;
title "MEPS, 2016";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_16 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt16f;
var totexp16;
domain nmiss_exp('1') ;
ods output domain=_overall_16;
run;
title "MEPS, 2018";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_18 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt18f;
var totexp18;
domain nmiss_exp('1') ;
ods output domain=_overall_18;
run;
title "MEPS, 2005";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_05 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt05f;
var totexp05;
domain nmiss_exp('1') ;
ods output domain=_overall_05;
run;
title "MEPS, 2007";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_07 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt07f;
var totexp07;
domain nmiss_exp('1') ;
ods output domain=_overall_07;
run;
title "MEPS, 2009";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_09 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt09f;
var totexp09;
domain nmiss_exp('1') ;
ods output domain=_overall_09;
run;
title "MEPS, 2012";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_12 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt12f;
var totexp12;
domain nmiss_exp('1') ;
ods output domain=_overall_12;
run;
title "MEPS, 2014";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_14 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt14f;
var totexp14;
domain nmiss_exp('1') ;
ods output domain=_overall_14;
run;
title "MEPS, 2016";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_16 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt16f;
var totexp16;
domain nmiss_exp('1') ;
ods output domain=_overall_16;
run;
title "MEPS, 2018";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_18 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt18f;
var totexp18;
domain nmiss_exp('1') ;
ods output domain=_overall_18;
run;
title "MEPS, 2005";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_05 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt05f;
var totexp05;
domain nmiss_exp('1') ;
ods output domain=_overall_05;
run;
title "MEPS, 2007";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_07 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt07f;
var totexp07;
domain nmiss_exp('1') ;
ods output domain=_overall_07;
run;
title "MEPS, 2009";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_09 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt09f;
var totexp09;
domain nmiss_exp('1') ;
ods output domain=_overall_09;
run;
title "MEPS, 2012";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_12 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt12f;
var totexp12;
domain nmiss_exp('1') ;
ods output domain=_overall_12;
run;
title "MEPS, 2014";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_14 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt14f;
var totexp14;
domain nmiss_exp('1') ;
ods output domain=_overall_14;
run;
title "MEPS, 2016";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_16 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt16f;
var totexp16;
domain nmiss_exp('1') ;
ods output domain=_overall_16;
run;
title "MEPS, 2018";
ods graphics off;
ods exclude all;
proc surveymeans data=new.FY_18 nobs sumwgt mean stderr sum ;
stratum varstr;
cluster varpsu;
weight perwt18f;
var totexp18;
domain nmiss_exp('1') ;
ods output domain=_overall_18;
run;
