proc print data=h50;
format some_date worddate. run;
proc print data=h60;
format some_date worddate. run;
proc print data=h70;
format some_date worddate. run;
proc print data=h79;
format some_date worddate. run;
proc print data=h89;
format some_date worddate. run;
proc print data=h97;
format some_date worddate. run;
proc print data=h105;
format some_date worddate. run;
proc print data=h113;
format some_date worddate. run;
proc print data=h121;
format some_date worddate. run;
proc print data=h129;
format some_date worddate. run;
proc print data=h138;
format some_date worddate. run;
proc print data=h147;
format some_date worddate. run;
proc print data=h155;
format some_date worddate. run;
proc print data=h163;
format some_date worddate. run;
proc print data=h171;
format some_date worddate. run;
proc print data=h181;
format some_date worddate. run;
proc print data=h50;
format some_date worddate.;
run;
proc print data=h60;
format some_date worddate.;
run;
proc print data=h70;
format some_date worddate.;
run;
proc print data=h79;
format some_date worddate.;
run;
proc print data=h89;
format some_date worddate.;
run;
proc print data=h97;
format some_date worddate.;
run;
proc print data=h105;
format some_date worddate.;
run;
proc print data=h113;
format some_date worddate.;
run;
proc print data=h121;
format some_date worddate.;
run;
proc print data=h129;
format some_date worddate.;
run;
proc print data=h138;
format some_date worddate.;
run;
proc print data=h147;
format some_date worddate.;
run;
proc print data=h155;
format some_date worddate.;
run;
proc print data=h163;
format some_date worddate.;
run;
proc print data=h171;
format some_date worddate.;
run;
proc print data=h181;
format some_date worddate.;
run;
title "Data set: h50";
proc print data=h50;
format some_date worddate.;
run;
title "Data set: h60";
proc print data=h60;
format some_date worddate.;
run;
title "Data set: h70";
proc print data=h70;
format some_date worddate.;
run;
title "Data set: h79";
proc print data=h79;
format some_date worddate.;
run;
title "Data set: h89";
proc print data=h89;
format some_date worddate.;
run;
title "Data set: h97";
proc print data=h97;
format some_date worddate.;
run;
title "Data set: h105";
proc print data=h105;
format some_date worddate.;
run;
title "Data set: h113";
proc print data=h113;
format some_date worddate.;
run;
title "Data set: h121";
proc print data=h121;
format some_date worddate.;
run;
title "Data set: h129";
proc print data=h129;
format some_date worddate.;
run;
title "Data set: h138";
proc print data=h138;
format some_date worddate.;
run;
title "Data set: h147";
proc print data=h147;
format some_date worddate.;
run;
title "Data set: h155";
proc print data=h155;
format some_date worddate.;
run;
title "Data set: h163";
proc print data=h163;
format some_date worddate.;
run;
title "Data set: h171";
proc print data=h171;
format some_date worddate.;
run;
title "Data set: h181";
proc print data=h181;
format some_date worddate.;
run;
