title "Sales h50";
proc print data = h50 noobs;
run;
title "Sales h60";
proc print data = h60 noobs;
run;
title "Sales h70";
proc print data = h70 noobs;
run;
title "Sales h79";
proc print data = h79 noobs;
run;
title "Sales h89";
proc print data = h89 noobs;
run;
title "Sales h97";
proc print data = h97 noobs;
run;
title "Sales h105";
proc print data = h105 noobs;
run;
title "Sales h113";
proc print data = h113 noobs;
run;
title "Sales h121";
proc print data = h121 noobs;
run;
title "Sales h129";
proc print data = h129 noobs;
run;
title "Sales h138";
proc print data = h138 noobs;
run;
title "Sales h147";
proc print data = h147 noobs;
run;
title "Sales h155";
proc print data = h155 noobs;
run;
title "Sales h163";
proc print data = h163 noobs;
run;
title "Sales h171";
proc print data = h171 noobs;
run;
title "Sales h181";
proc print data = h181 noobs;
run;
