proc means data = sashelp.class (where =(1));
var height;
title "sashelp.class height 1";
run;
proc means data = sashelp.class (where =(sex eq 'F'));
var height;
title "sashelp.class height sex eq 'F'";
run;
proc means data = sashelp.class (where =(sex eq 'M'));
var height;
title "sashelp.class height sex eq 'M'";
run;
proc means data = sashelp.class (where =(1));
var weight;
title "sashelp.class weight 1";
run;
proc means data = sashelp.class (where =(sex eq 'F'));
var weight;
title "sashelp.class weight sex eq 'F'";
run;
proc means data = sashelp.class (where =(sex eq 'M'));
var weight;
title "sashelp.class weight sex eq 'M'";
run;
proc means data = sashelp.shoes (where =(1));
var sales;
title "sashelp.shoes sales 1";
run;
