dm "clear log; clear output; clear odsresults;";
proc format;
  value major_fmt 1='STAT' 2='ECON' 3='MATH';
run;
data students;
  do i = 1 to 25;
     fake_id = cats('Student',put(i, z3.));
     simulated_var = 1 + int(3*ranuni(23409));
     major = put(simulated_var, major_fmt.);
     output;
  end;
  drop i simulated_var;
run;
proc print data=students;
run;
proc freq data=students;
  tables major;
run;
proc contents data=students varnum ;
ods select position;
run;

proc datasets lib=work memtype=data nolist;
     modify students;
     attrib _all_ format=;
	run;
quit;
proc contents data=students varnum;
ods select position;
run;
